{% set name = "attune" %}
{% set version = "0.2.0" %}
{% set sha256 = "aa6bb723e0e65306699570030a26049e94e35bb1c5dadc8b68927fbe3176d0cf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python >=3.5
    - pip
    - setuptools
    - pytest-runner
  run:
    - python >=3.5
    - WrightTools >=3.2.5
    - numpy
    - scipy
    - matplotlib-base
    - tidy_headers

test:
  imports:
    - attune

about:
  home: https://github.com/wright-group/attune
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tools for tuning optical parametric amplifiers and multidimensional spectrometers.

extra:
  recipe-maintainers:
    - untzag
    - ksunden
