travis:
  secure:
    BINSTAR_TOKEN: toJl2TP/717SJ9qO3729wMerURS/IwvZRJN1MGOLJoYwsVa7thdIVrNZDGjHd8iWb6Zs7mC0wXKPc0XNcXVCGrKzFcLT4f0zUv7kqpTL97YCk4TjGY5fxiUXNjoyIeTWtVSghexoza/joRffbiWbV+hN909KKbYeWUFPfGju8UkaIMEpctKFAHjPzY5uGmU0Ll1CQ23S45VgqmxNyNEI+2m1Eko4k+I1qKIn+EqHWcClhITrSB5yg9+gcjxlhY+5/7Q/SH7Kodvvynj2P36kn6gKsrJ5KEa8P1Wti+PVq/RgAxTwPUJJ+cXWoRCzwcNRcSNrU4Rxx2PVPoGTILYIaEYVaAOZyjhszRCXmEBvz79IFKKZtAQDkpdEzQXQz/qg5BVZUDZ3qsPMRJY6SeIeBmlyxMKAGVNspSNe9Fp8+vNqx8pPGjRpZtYGw6neVyzYqJMvoNxQRYIO20p1LRe+7SR33ljheIDxsJrBofPvLJZX8+iw/QPThm8n8b/pmpxogMbn02Uw6gZZ9mg8ZND19LmgOfZBqLNDH3u1s+0A/EUGttePUur8ouqmZQ2TsSLKrQgrl4zTYfBxj19wHTR3nqgKv6s8WpHldRkTGlHxcZMMWL0sSAYKomAmMG/Ia483FHmn78Unjq5asqyOK8czYOsEnBF1gL1zZKP8XJRcSlc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
